site_name: SAUS Citation Guide
site_url: https://saus-journal.github.io/citation-guide/

theme:
  name: material
  language: en
  palette:
    - scheme: default        # Light mode
      primary: indigo
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      media: "(prefers-color-scheme: light)"
    - scheme: slate          # Dark mode
      primary: indigo
      accent: pink
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      media: "(prefers-color-scheme: dark)"
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.expand
    - navigation.external-links-new-tab

extra_css:
  - css/typography.css

markdown_extensions:
  - md_in_html
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: true
  - footnotes
  - tables

plugins:
  - search
  - i18n:
      docs_structure: suffix
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: bg
          name: Български
          build: true
          nav_translations:
            Home: Начало
            Citation essentials: Същина на позоваването
            Types of referenced works: Видове реферирани трудове
            Components of reference entry: Компоненти на библиографския запис
            Saus Citation Style: Стил на позоваване на SAUS
            Introduction: Увод
            Creators: Създатели
            

nav:
  - Home: index.md
  - Citation essentials:      
    - Types of referenced works: citation_essentials/types_of_scholarly_works.md
    - Components of reference entry: citation_essentials/components_of_reference_entry.md
  - Saus Citation Style:
    - Introduction: saus_citation_style/introduction.md
    - Creators: saus_citation_style/creators.md
