site_name: SAUS Citation Guide
site_url: https://saus-journal.github.io/citation-guide/

theme:
  name: material
  language: en
  palette:
    - scheme: default        # Light mode
      primary: indigo
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      media: "(prefers-color-scheme: light)"
    - scheme: slate          # Dark mode
      primary: indigo
      accent: pink
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      media: "(prefers-color-scheme: dark)"

plugins:
  - search
  - i18n:
      docs_structure: suffix
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: bg
          name: Български
          build: true
          nav_translations:
            HOME: НАЧАЛО
            CITATION ESSENTIALS: ОСНОВНИ ПРИНЦИПИ
            TYPES OF SCHOLARLY WORKS: ВИДОВЕ НАУЧНИ ПРОИЗВЕДЕНИЯ
            COMPONENTS OF REFERENCE ENTRY: КОМПОНЕНТИ НА БИБЛИОГРАФСКИЯ ЗАПИС
            

nav:
  - HOME: index.md
  - CITATION ESSENTIALS:
    - TYPES OF SCHOLARLY WORKS: types_of_scholarly_works.md
    - COMPONENTS OF REFERENCE ENTRY: components_of_reference_entry.md
