site_name: Citation Guide

theme:
  name: material
  language: en
  palette:
    - scheme: default        # Light mode
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      media: "(prefers-color-scheme: light)"
    - scheme: slate          # Dark mode
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      media: "(prefers-color-scheme: dark)"

plugins:
  - search
  - i18n:
      docs_structure: suffix
      default_language: en
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: bg
          name: Български
          build: true

nav:
  - Home: index.md
